export interface Course {
  title: string
  description: string
  href: string
  price: string
  image: string
}

export interface StaffMember {
  name: string
  role: string
  bio: string
  image?: string
}

export interface Announcement {
  title: string
  date: string
  description: string
  category: string
  href?: string
}

export interface Service {
  title: string
  description: string
  icon: string
  href?: string
}

export const siteConfig = {
  name: "Lavanika Academy",
  tagline: "Ace Your ADC Exam",
  description: "Expert-led preparation for every stage of the ADC exam — live coaching, real mock exams, and a community that's already helped 1,200+ overseas dentists pass.",
  email: "info@lavanika.academy",
  phone: "+61 468434447",
  whatsapp: "https://wa.me/61468434447",
  address: "Suite 205, 838 Collins St, Docklands, VIC 3008",
  facebook: "https://www.facebook.com/groups/863282811046580/?ref=share_group_link",
  instagram: "https://www.instagram.com/lavanika_academy/",
  studentPortal: "https://study.lavanika.academy",
  founded: 2019,
  candidatesTrained: 1200,
  countriesReached: 25,
  liveHours: 4000,
  communityMembers: 1000,
  reviews: 119,
  rating: 5.0,
  companyName: "Lavanika Academy Pty Ltd",
  year: 2026,
}

export interface CourseDetail {
  title: string
  description: string
  longDescription: string
  href: string
  image: string
  category: string
  duration: string
  durationLabel: string
  location: string
  startTime: string
  fee: string
  feeOriginal?: string
  availability: string
  features?: string[]
  whoFor: string[]
  whatYouLearn: string[]
  modules?: { title: string; items: string[] }[]
  whatToBring: string[]
  tasksLabel: string
  materialsIncluded: string
  demosIncluded: string
  accessDuration: string
  faq: { q: string; a: string }[]
  stripeUrl: string
}

export interface StudentPortalResource {
  title: string
  description: string
  icon: string
  href?: string
}

export const courseDetails: CourseDetail[] = [
  {
    title: "Communication OSCE course - Basic package",
    description: "Prepare for all ADC communication stations through 8 live roleplay sessions, structured feedback, and proven frameworks taught by Dr Lavanika.",
    longDescription: "This 9 to 10-week online course is designed for overseas-trained dentists preparing for the ADC Communication OSCE. Led entirely by Dr. Lavanika, each session focuses on real scenarios, structured roleplays, and detailed feedback — helping you build confidence, structure, and empathy. You'll attend 3–4 live sessions weekly, each lasting 2–3 hours, in a small-group setting. Every candidate performs roleplays, followed by individual feedback. You'll also get recordings of your batch, access to a private discussion group, and extended support up until your exam day.",
    href: "/courses/communication-osce/communication-osce-course-8-roleplays",
    image: "/images/courses/communication-osce-course-8.webp",
    category: "Communication OSCE",
    duration: "9",
    durationLabel: "9 to 10 weeks",
    location: "Online",
    startTime: "7 pm Melbourne time",
    fee: "$ 1,699 (AUD)",
    feeOriginal: "$ 1,999 (AUD)",
    availability: "Contact us for availability",
    features: ["8 live roleplay sessions (1 per week)", "Structured feedback after each session", "Proven frameworks for all station types", "Small batch size for personal attention", "3-4 live sessions per week (2-3 hrs each)", "Full session recordings access for 1 year", "Private Facebook Messenger group", "Resource drive with scenarios & outlines", "Recent ADC changes info near exam"],
    whoFor: ["Candidates sitting the ADC Practical Exam (Clinical Skills Day)", "Dentists who want to refine patient communication and consultation techniques", "Those struggling with structuring responses under time pressure"],
    whatYouLearn: ["Structured approach to any Communication OSCE task", "Fluency and confidence under pressure", "Examiner expectations and scoring rubric", "Techniques to build rapport and manage challenging patients"],
    modules: [{ title: "Course Format", items: ["Online via GoTo Meeting", "Conducted by Dr. Lavanika", "Main sessions: Tuesday, Thursday", "Roleplay days: Monday, Wednesday, Friday, Sunday", "9 to 10 weeks of live sessions", "Camera-on encouraged for real-time feedback"] }],
    whatToBring: ["Notebook and pen", "Reliable internet connection", "Camera and microphone for video sessions"],
    tasksLabel: "8 roleplays",
    materialsIncluded: "Yes",
    demosIncluded: "N/A (roleplay-based)",
    accessDuration: "1 year",
    faq: [{ q: "How long does the Communication OSCE course - Basic package run?", a: "It runs for 9 to 10 weeks, giving you sustained coaching and practice time." }, { q: "Where do I attend the sessions?", a: "All live teaching happens online so you can participate from wherever you are." }, { q: "What time are the live sessions scheduled?", a: "Sessions typically start at 7 pm Melbourne time." }, { q: "How many roleplays are included in this package?", a: "You will complete 8 roleplays - one per week across the 8-week practice block." }, { q: "What is the fee for this course?", a: "Enrollment is $1,699, covering all live sessions, resources, and feedback." }],
    stripeUrl: "https://book.stripe.com/00g8yJ9pJ8iJ8zS288",
  },
  {
    title: "Communication OSCE course - Extra roleplay package",
    description: "Comprehensive preparation with 16 live roleplay sessions — double the practice, double the confidence.",
    longDescription: "This 9 to 10-week online course is designed for overseas-trained dentists preparing for the ADC Communication OSCE. Led entirely by Dr. Lavanika, each session focuses on real scenarios, structured roleplays, and detailed feedback. You'll attend 3-4 live sessions weekly in a small-group setting. Every candidate performs 2 roleplays per week, followed by individual feedback.",
    href: "/courses/communication-osce/communication-osce-course-16-roleplays",
    image: "/images/courses/communication-osce-course-16.webp",
    category: "Communication OSCE",
    duration: "9",
    durationLabel: "9 to 10 weeks",
    location: "Online",
    startTime: "7 pm Melbourne time",
    fee: "$ 2,599 (AUD)",
    feeOriginal: "$ 2,999 (AUD)",
    availability: "Contact us for availability",
    features: ["16 live roleplay sessions (2 per week)", "Extended feedback and coaching", "All station types covered", "Small batch size", "3-4 live sessions per week", "Full session recordings for 1 year", "Private Facebook Messenger group", "Resource drive", "Recent changes info near exam"],
    whoFor: ["Candidates wanting extra roleplay practice", "Dentists needing more repetition to build fluency", "Those preparing intensively for the ADC Clinical Skills Day"],
    whatYouLearn: ["Master any Communication OSCE task type", "Advanced fluency and confidence", "Deep understanding of examiner scoring", "Handling complex patient scenarios"],
    modules: [{ title: "Course Format", items: ["Online via GoTo Meeting", "Conducted by Dr. Lavanika", "Main sessions: Tuesday, Thursday", "Roleplay days: Monday, Wednesday, Friday, Sunday", "9 to 10 weeks", "Camera-on encouraged"] }],
    whatToBring: ["Notebook and pen", "Reliable internet connection", "Camera and microphone"],
    tasksLabel: "16 roleplays (2 per week)",
    materialsIncluded: "Yes",
    demosIncluded: "N/A (roleplay-based)",
    accessDuration: "1 year",
    faq: [{ q: "How long does the extra roleplay package run?", a: "It runs for 9 to 10 weeks." }, { q: "Where are classes delivered?", a: "Every session is hosted online via GoTo Meeting." }, { q: "What time should I be available?", a: "Live teaching begins at 7 pm Melbourne time." }, { q: "How many roleplays are included?", a: "You will complete 16 roleplays - two per week across 8 weeks." }, { q: "What does the course cost?", a: "Fee for the extra roleplay package is $2,599." }],
    stripeUrl: "https://book.stripe.com/28o02d1Xh6aB3fyfZj",
  },
  {
    title: "Communication OSCE course - Recordings & Roleplay package",
    description: "Self-paced access to recorded sessions plus 8 live roleplays in a future batch.",
    longDescription: "Not ready for a full live batch but still want real roleplay practice? This package gives you the best of both worlds: full recordings from a current or previous batch to study on your own schedule, plus 8 live roleplays in a future batch to put your skills into practice.",
    href: "/courses/communication-osce/communication-osce-course-recordings-roleplay",
    image: "/images/courses/communication-osce-course-8.webp",
    category: "Communication OSCE",
    duration: "Self-paced",
    durationLabel: "Self-paced + future batch roleplays",
    location: "Online",
    startTime: "-",
    fee: "$ 1,699 (AUD)",
    feeOriginal: "$ 1,999 (AUD)",
    availability: "Contact us for availability",
    features: ["Full batch recordings for self-study", "8 live roleplays in future batch (1 per week)", "Live feedback after every roleplay", "Resource drive with scenarios", "Private Facebook Messenger group", "1-year access to recordings", "Recent changes info near exam"],
    whoFor: ["Candidates who cannot commit to live teaching sessions", "Dentists preparing in advance who want to self-study first", "Those looking for a flexible entry point"],
    whatYouLearn: ["Structured approach to any Communication OSCE task", "Examiner expectations and scoring rubric", "Techniques to build rapport and manage patients", "History-taking, consent, bad news, and complaints"],
    modules: [],
    whatToBring: ["Reliable internet connection", "Camera and microphone for roleplay sessions"],
    tasksLabel: "8 roleplays in future batch",
    materialsIncluded: "Yes (recordings)",
    demosIncluded: "N/A",
    accessDuration: "1 year",
    faq: [{ q: "What is included?", a: "Full batch recordings to study at your own pace, plus 8 scheduled roleplays in a future batch." }, { q: "Do I attend live teaching sessions?", a: "No. You study through recordings and participate only in the 8 roleplay sessions." }, { q: "When do roleplays take place?", a: "Once allocated to a future batch, 1 roleplay per week for 8 weeks." }, { q: "How long is access?", a: "1 year from enrolment." }, { q: "What is the fee?", a: "$1,699 (AUD)." }],
    stripeUrl: "https://book.stripe.com/aFa4gA4yb0Bd6tdh2F08g0A",
  },
  {
    title: "Communication OSCE course - Course Records",
    description: "Complete course recordings for self-paced study of Communication OSCE.",
    longDescription: "Can't join a live batch right now? This self-paced package gives you full access to the recordings of one complete Communication OSCE batch - so you can study Dr. Lavanika's teaching on your own schedule, without missing a thing.",
    href: "/courses/communication-osce/communication-osce-course-records",
    image: "/images/courses/communication-osce-course-8.webp",
    category: "Communication OSCE",
    duration: "Self-paced",
    durationLabel: "Self-paced",
    location: "Online",
    startTime: "-",
    fee: "$ 1,499 (AUD)",
    availability: "Contact us for availability",
    features: ["Full batch recordings", "Resource drive with scenarios & outlines", "Private Facebook Messenger group", "1-year access to all materials", "Recent changes info near exam"],
    whoFor: ["Candidates who cannot attend a live batch", "Dentists who prefer self-paced study", "Those seeking cost-effective access to expert coaching"],
    whatYouLearn: ["Structured approach to any Communication OSCE task", "Examiner expectations and scoring rubric", "Techniques to build rapport", "History-taking, consent, bad news, complaints"],
    modules: [],
    whatToBring: ["Reliable internet connection"],
    tasksLabel: "None (recordings only)",
    materialsIncluded: "Yes",
    demosIncluded: "N/A",
    accessDuration: "1 year",
    faq: [{ q: "What is included?", a: "Complete recordings from one full batch plus all study materials." }, { q: "Are there live sessions?", a: "No. This is self-paced with recorded sessions only." }, { q: "How long is access?", a: "1 year from enrolment." }, { q: "Can I get support?", a: "Yes, via the private Facebook group." }, { q: "What is the fee?", a: "$1,499 (AUD)." }],
    stripeUrl: "https://book.stripe.com/9AQdT345pcyZaI0aF8",
  },
  {
    title: "Skilled OSCE Beginner Course",
    description: "Comprehensive 2-day beginner course covering all ADC Skilled OSCE stations from the ground up.",
    longDescription: "This course is specifically designed for overseas-qualified dentists preparing for the Skilled OSCE section of the ADC Practical Examination. The course includes skilled osce simulation-based practice, task execution, and examiner-focused performance strategies.",
    href: "/courses/skilled-osce/skilled-osce-beginner",
    image: "/images/courses/skilled-osce-beginner.webp",
    category: "Skilled OSCE",
    duration: "2",
    durationLabel: "2 days",
    location: "Onsite",
    startTime: "9:30 am to 4:30 pm",
    fee: "$ 1,499 (AUD)",
    availability: "Contact us for availability",
    features: ["2-day comprehensive training", "All skilled stations covered: X-Ray, LA, Extraction, CPR, Syncope, Scaling, PFS, Rubber Dam, Matrix Band", "Hands-on practice after each task demo", "Detailed instructor feedback", "Study materials included", "1-year access to materials"],
    whoFor: ["Overseas-trained dentists eligible for ADC Practical Exam", "Candidates seeking confidence in typodont and manikin-based tasks", "Dentists aiming for mastery in time-bound procedural OSCE scenarios"],
    whatYouLearn: ["Execute skilled osce task procedures with precision", "Apply global rating and checklist criteria used by examiners", "Understand examiner expectations and feedback patterns"],
    modules: [{ title: "Module 1: Introduction to Skilled OSCE", items: ["Overview of ADC exam format", "Understanding the rubric and scoring"] }, { title: "Module 2: Hands-on Procedural Training", items: ["Each task detailed demo", "Infection control and setup protocols", "Practice time after each task demo"] }, { title: "Module 3: Exam Strategy and Practice", items: ["Common examiner errors to avoid", "Time management techniques"] }],
    whatToBring: ["ADC jaws (magnetic)", "Rubber dam sheets", "Plastic instrument", "Pit and fissure sealants", "Matrix bands", "Eyewear"],
    tasksLabel: "All skilled OSCE tasks",
    materialsIncluded: "Bring your own for practice",
    demosIncluded: "Yes, all tasks",
    accessDuration: "1 year",
    faq: [{ q: "How long is the Skilled OSCE beginner course?", a: "The beginner course runs for 2 days of intensive practical training." }, { q: "What do I need to bring?", a: "Please bring your ADC jaws (magnetic), rubber dams, plastic instrument, pit and fissure sealants and matrix bands." }, { q: "Where is this course delivered?", a: "Training takes place at Lavanika Academy center in Melbourne." }, { q: "What time should I attend?", a: "Sessions begin at 9:30 am Melbourne time." }, { q: "Does this course include practice time?", a: "Yes, after each task demo you will get time to practice." }, { q: "What is the course fee?", a: "Enrollment for the beginner course is $1,499." }],
    stripeUrl: "https://book.stripe.com/eVa3epeK30Qh5nG8wY",
  },
  {
    title: "Skilled OSCE Refresher Course",
    description: "A focused 1-day refresher for candidates who have prior Skilled OSCE experience.",
    longDescription: "This course is specifically designed for overseas-qualified dentists preparing for the Skilled OSCE section of the ADC Practical Examination. It is a one day Refresher Course and includes skilled osce simulation-based practice, task execution, and examiner-focused performance strategies.",
    href: "/courses/skilled-osce/skilled-osce-refresher",
    image: "/images/courses/skilled-osce-refresher.webp",
    category: "Skilled OSCE",
    duration: "1",
    durationLabel: "1 day",
    location: "Onsite",
    startTime: "9:30 am to 4:30 pm",
    fee: "$ 899 (AUD)",
    availability: "Contact us for availability",
    features: ["1-day focused refresher", "All skilled stations covered (except rubber dam & matrix band demo)", "Hands-on practice", "Instructor feedback", "Study materials included", "1-year access"],
    whoFor: ["Overseas-trained dentists eligible for ADC Practical Exam", "Candidates who have prior ADC preparation experience", "Dentists wanting quick revision before the exam"],
    whatYouLearn: ["Execute skilled osce tasks with precision", "Apply examiner checklist criteria", "Understanding examiner expectations"],
    modules: [{ title: "Module 1: Introduction", items: ["ADC exam format overview", "Rubric and scoring"] }, { title: "Module 2: Procedural Training", items: ["Each task demo (except rubber dam & matrix band)", "Infection control protocols", "Practice time"] }, { title: "Module 3: Exam Strategy", items: ["Common errors", "Time management"] }],
    whatToBring: ["ADC jaws (magnetic)", "Rubber dam sheets", "Plastic instrument", "Pit and fissure sealants", "Matrix bands", "Eyewear"],
    tasksLabel: "All tasks (demos except rubber dam & matrix band)",
    materialsIncluded: "Bring your own for practice",
    demosIncluded: "Yes, except rubber dam & matrix band",
    accessDuration: "1 year",
    faq: [{ q: "How long is the refresher course?", a: "The refresher course runs for 1 day." }, { q: "What do I need to bring?", a: "ADC jaws, rubber dams, plastic instrument, PFS, matrix bands, eyewear." }, { q: "Where is it delivered?", a: "Lavanika Academy centre in Melbourne." }, { q: "Session times?", a: "9:30 am to 4:30 pm Melbourne time." }, { q: "What is the fee?", a: "$899 (AUD)." }],
    stripeUrl: "https://book.stripe.com/5kA7uFcBVbuV5nGaEO",
  },
  {
    title: "Technical Skills Beginner Course",
    description: "Comprehensive 2-week onsite beginner course covering all ADC technical stations.",
    longDescription: "This course is specially designed for overseas-qualified dentists preparing for the Technical Skills Day of the ADC Practical Examination. The course emphasises both preparation and restoration tasks in a simulated clinical environment, combining expert-led demos, hands-on practice, one-on-one feedback, and improvement plans.",
    href: "/courses/technical-skills/technical-skills-beginner",
    image: "/images/courses/technical-skills-beginner.webp",
    category: "Technical Skills",
    duration: "2",
    durationLabel: "2 weeks",
    location: "Onsite",
    startTime: "9:30 am Monday to Friday",
    fee: "$ 5,500 (AUD)",
    availability: "Next batch: 15 June 2026",
    features: ["2-week intensive programme", "All 6 core restoration & preparation tasks", "Live demos each morning", "Hands-on practice each afternoon", "One-on-one feedback & improvement plan", "Mock exam on last day", "Small batch (less than 6 candidates)", "1-year access to materials"],
    whoFor: ["Overseas-trained dentists eligible for ADC practical exam", "Candidates aiming to master restoration and preparation stations", "Those wanting one-on-one mentorship and detailed feedback"],
    whatYouLearn: ["Confidence in performing six core restoration & preparation tasks", "Familiarity with ADC-style assessment criteria", "Precision in margins, contacts, occlusion, anatomy, finish", "Speed, workflow efficiency and safe practice"],
    modules: [{ title: "Daily Format", items: ["Morning: Instructor demo of task", "Afternoon: Hands-on practice under supervision", "Evening: Individualised feedback & improvement plan"] }],
    whatToBring: ["ADC jaws (magnetic)", "Fletcher", "Teeth", "Material for tasks", "Instruments, handpiece, burs", "Eyewear and loupes"],
    tasksLabel: "All tasks",
    materialsIncluded: "Email us for list",
    demosIncluded: "Yes, all tasks",
    accessDuration: "1 year",
    faq: [{ q: "How long is the technical skills beginner course?", a: "This workshop runs for 2 weeks." }, { q: "What do I need to bring?", a: "Please email info@lavanika.academy for the complete materials list." }, { q: "Where is it delivered?", a: "Lavanika Academy centre in Melbourne." }, { q: "Session times?", a: "9:30 am Melbourne time, Monday to Friday." }, { q: "Does it include a mock exam?", a: "Yes, one mock exam is included on the last day." }, { q: "What is the fee?", a: "$5,500 (AUD)." }],
    stripeUrl: "https://book.stripe.com/6oE9CNbxRfLb9DW28v",
  },
  {
    title: "Technical Skills Refresher Course",
    description: "1-week refresher for candidates who have completed basic technical skills training.",
    longDescription: "This course is specially designed for overseas-qualified dentists preparing for the Technical Skills Day of the ADC Practical Examination. It focuses on simulation-based, restoration and preparation procedural tasks and time-bound practice.",
    href: "/courses/technical-skills/technical-skills-refresher",
    image: "/images/courses/technical-skills-refresher.webp",
    category: "Technical Skills",
    duration: "1",
    durationLabel: "1 week",
    location: "Onsite",
    startTime: "9:30 am Monday to Friday",
    fee: "$ 3,000 (AUD)",
    availability: "Contact us for availability",
    features: ["1-week intensive refresher", "Choose 2 tasks from 6 options", "Expert demos", "Hands-on practice", "Instructor feedback", "Small batch size", "1-year access"],
    whoFor: ["Candidates who have previously undergone ADC preparation", "Those looking for quick effective revision before the exam"],
    whatYouLearn: ["Refine speed and precision", "ADC marking criteria application", "Time management under exam conditions"],
    modules: [{ title: "Module 1: Foundation & Setup", items: ["Simulation unit orientation", "Manikin head and typodont handling", "Infection control and ergonomics"] }, { title: "Module 2: Preparation Tasks", items: ["Carious tooth preparation", "Crown preparation", "Endodontic access preparation"] }, { title: "Module 3: Restoration Tasks", items: ["Resin composite (posterior)", "Resin composite (anterior)", "Provisional for crown", "Polishing and evaluation"] }, { title: "Module 4: Mock Stations", items: ["Six-task simulation", "Real-time feedback", "Improvement plan"] }],
    whatToBring: ["ADC jaws (magnetic)", "Teeth", "Material for tasks", "Instruments", "Eyewear and loupes"],
    tasksLabel: "Choose 2 of 6 tasks",
    materialsIncluded: "Email us for list",
    demosIncluded: "Yes, 2 tasks",
    accessDuration: "1 year",
    faq: [{ q: "How long is the refresher course?", a: "1 week." }, { q: "What do I need to bring?", a: "Email info@lavanika.academy for the materials list." }, { q: "Where is it delivered?", a: "Lavanika Academy, Melbourne." }, { q: "Session times?", a: "9:30 am Melbourne time." }, { q: "Does it include a mock exam?", a: "No, mock exam is included in the full course." }, { q: "What is the fee?", a: "$3,000 (AUD)." }],
    stripeUrl: "https://book.stripe.com/00g3epcBV42t2bu7sQ",
  },
  {
    title: "Clinical OSCE Mock Exam",
    description: "Full 4-hour mock combining 6 Communication & 4 Skilled OSCE tasks.",
    longDescription: "Our most comprehensive half-day mock, designed to simulate the complete ADC Clinical Skills Day. Practice both 6 Communication OSCE tasks and 4 Skilled OSCE tasks under realistic exam conditions with expert feedback from Dr. Lavanika.",
    href: "/courses/mock-exams/clinical-osce-mock-exam",
    image: "/images/courses/communication-osce-mock-exam.webp",
    category: "Mock Exams",
    duration: "4",
    durationLabel: "4 hours",
    location: "Onsite",
    startTime: "9:30 am to 1:30 pm",
    fee: "$ 595 (AUD)",
    availability: "Contact us for availability",
    features: ["6 Communication OSCE roleplays", "4 Skilled OSCE procedural tasks", "Timed ADC-format stations", "Verbal and written feedback", "Performance summary", "Materials provided"],
    whoFor: ["ADC candidates preparing for Clinical Skills Day", "Dentists wanting to assess readiness", "Those seeking structured expert feedback"],
    whatYouLearn: ["Experience real exam conditions", "Identify strengths and weaknesses", "Receive targeted improvement suggestions"],
    modules: [],
    whatToBring: ["Eyewear only - all materials provided"],
    tasksLabel: "6 Communication & 4 Skilled OSCEs",
    materialsIncluded: "Provided",
    demosIncluded: "Not included",
    accessDuration: "N/A",
    faq: [{ q: "What does it include?", a: "6 Communication OSCE roleplays and 4 Skilled OSCE tasks." }, { q: "How long is it?", a: "4 hours (9:30 am to 1:30 pm)." }, { q: "Where is it held?", a: "Lavanika Academy, Melbourne." }, { q: "What to bring?", a: "Just your eyewear. All materials provided." }, { q: "Is feedback provided?", a: "Yes, structured feedback from Dr. Lavanika." }, { q: "What is the fee?", a: "$595 (AUD)." }],
    stripeUrl: "https://book.stripe.com/9AQg1bcBV9mNbM44gt",
  },
  {
    title: "Communication OSCE Mock Exam",
    description: "3-hour mock with 6 Communication OSCE roleplays and detailed feedback.",
    longDescription: "Prepare effectively for the ADC Communication OSCE with this mock exam designed to simulate the real testing environment. Practice, refine, and receive feedback - all under expert guidance from Dr. Lavanika.",
    href: "/courses/mock-exams/communication-osce-mock-exam",
    image: "/images/courses/communication-osce-mock-exam.webp",
    category: "Mock Exams",
    duration: "3",
    durationLabel: "3 hours",
    location: "Onsite",
    startTime: "9:30 am to 12:30 pm",
    fee: "$ 550 (AUD)",
    availability: "Contact us for availability",
    features: ["6 Communication OSCE roleplays", "1-on-1 with Dr. Lavanika", "Immediate verbal feedback", "Detailed performance summary", "Weekly slots available"],
    whoFor: ["ADC Part 2 candidates preparing for Communication OSCE", "Dental professionals seeking practical revision"],
    whatYouLearn: ["Real exam simulation experience", "Identify areas for improvement", "Understand examiner expectations"],
    modules: [],
    whatToBring: ["Nothing required"],
    tasksLabel: "6 Communication OSCEs",
    materialsIncluded: "N/A",
    demosIncluded: "Not applicable",
    accessDuration: "N/A",
    faq: [{ q: "How long is it?", a: "3 hours (9:30 am to 12:30 pm)." }, { q: "Where is it held?", a: "Lavanika Academy, Melbourne." }, { q: "What should I bring?", a: "Nothing required for communication osce mock." }, { q: "How many roleplays?", a: "6 roleplays." }, { q: "Is feedback provided?", a: "Yes, written feedback by Dr. Lavanika." }, { q: "What is the fee?", a: "$550 (AUD)." }],
    stripeUrl: "https://book.stripe.com/6oE4itdFZ7eF5nG3cH",
  },
  {
    title: "Skilled OSCE mock exam",
    description: "4-hour mock covering all 9 Skilled OSCE tasks with expert feedback.",
    longDescription: "Practice all Skilled OSCE tasks in a realistic mock setting designed to boost your confidence, accuracy, and clinical readiness for the ADC Clinical Examination.",
    href: "/courses/mock-exams/skilled-osce-mock-exam",
    image: "/images/courses/skilled-osce-mock-exam.webp",
    category: "Mock Exams",
    duration: "4",
    durationLabel: "4 hours",
    location: "Onsite",
    startTime: "9:30 am to 1:30 pm",
    fee: "$ 590 (AUD)",
    availability: "Contact us for availability",
    features: ["All 9 Skilled OSCE task types", "Timed ADC-format stations", "Verbal + written feedback", "Performance evaluation", "Materials provided"],
    whoFor: ["Final-stage ADC Part 2 candidates", "Overseas-trained dentists preparing for Skilled OSCE", "Dental professionals seeking real-time mock practice"],
    whatYouLearn: ["Full simulation experience", "Identify skill gaps", "Receive targeted improvement suggestions"],
    modules: [],
    whatToBring: ["Eyewear only - all materials provided"],
    tasksLabel: "9 Skilled OSCEs",
    materialsIncluded: "Provided",
    demosIncluded: "Not included",
    accessDuration: "N/A",
    faq: [{ q: "How long is it?", a: "Half day (4 hours)." }, { q: "Where is it held?", a: "Lavanika Academy, Melbourne." }, { q: "What should I bring?", a: "Just your eyewear. Everything else provided." }, { q: "Are all skilled tasks covered?", a: "Yes, all skilled osce tasks are covered with feedback." }, { q: "Is there practice time?", a: "No, mock exams do not include practice time." }, { q: "What is the fee?", a: "$590 (AUD)." }],
    stripeUrl: "https://book.stripe.com/7sI8yJ45pcyZ5nG3cq",
  },
  {
    title: "Technical skills mock exam",
    description: "Full-day mock covering 3 restoration and 3 preparation tasks.",
    longDescription: "Refine your clinical hand skills and confidence with Lavanika Academy's focused mock exam covering 3 restoration and 3 preparation tasks - tailored to the ADC Part 2 Technical skills exam.",
    href: "/courses/mock-exams/technical-skills-mock-exam",
    image: "/images/courses/technical-skills-mock-exam.webp",
    category: "Mock Exams",
    duration: "1",
    durationLabel: "1 day",
    location: "Onsite",
    startTime: "9:30 am to 4:30 pm",
    fee: "$ 900 (AUD)",
    availability: "Contact us for availability",
    features: ["3 restoration tasks (composite post, composite ant, provisional)", "3 preparation tasks (caries, endo, crown prep)", "Real-time ADC simulation", "One-on-one feedback", "Photo/video review", "Materials provided"],
    whoFor: ["ADC candidates preparing for Technical Skills OSCE", "Dentists needing practice in clinical hand skills", "Final revision candidates"],
    whatYouLearn: ["Improve speed and precision", "Exam-style feedback on technique", "Identify weaknesses and receive corrections"],
    modules: [],
    whatToBring: ["Eyewear and loupes - all other materials provided"],
    tasksLabel: "3 restoration & 3 preparation",
    materialsIncluded: "Provided",
    demosIncluded: "Not included",
    accessDuration: "N/A",
    faq: [{ q: "How long is it?", a: "Full day (9:30 am to 4:30 pm)." }, { q: "Where is it held?", a: "Lavanika Academy, Melbourne." }, { q: "What should I bring?", a: "Eyewear and loupes. Everything else provided." }, { q: "What tasks are covered?", a: "3 preparation and 3 restoration tasks." }, { q: "Is there practice time?", a: "No, mock exams do not include practice time." }, { q: "What is the fee?", a: "$900 (AUD)." }],
    stripeUrl: "https://book.stripe.com/7sIbKV7hBbuV5nGcN1",
  },
  {
    title: "Communication OSCE Mini Mock Exam",
    description: "Focused 1.5-hour mini mock for quick Communication OSCE assessment.",
    longDescription: "A shorter, focused mock exam for candidates who want a quick assessment of their communication skills. Ideal for final revision or a quick check-in before the real exam.",
    href: "/courses/mock-exams/communication-osce-mini-mock-exam",
    image: "/images/courses/communication-osce-mock-exam.webp",
    category: "Mock Exams",
    duration: "1.5",
    durationLabel: "1.5 hours",
    location: "Onsite",
    startTime: "Flexible",
    fee: "$ 300 (AUD)",
    availability: "Contact us for availability",
    features: ["2-3 Communication OSCE roleplays", "Quick assessment format", "Focused feedback", "Flexible scheduling"],
    whoFor: ["Candidates wanting quick assessment", "Those in final revision phase", "Dentists wanting to check readiness"],
    whatYouLearn: ["Quick performance check", "Targeted improvement areas"],
    modules: [],
    whatToBring: ["Nothing required"],
    tasksLabel: "2-3 roleplays",
    materialsIncluded: "N/A",
    demosIncluded: "Not applicable",
    accessDuration: "N/A",
    faq: [{ q: "How long is it?", a: "1.5 hours." }, { q: "Where is it held?", a: "Lavanika Academy, Melbourne." }, { q: "What is the fee?", a: "$300 (AUD)." }],
    stripeUrl: "https://book.stripe.com/",
  },
  {
    title: "ADC Written Exam - Coaching Program",
    description: "Structured 6-month live coaching for the ADC Written Exam with Dr. Samy.",
    longDescription: "Prepare for the ADC Written Exam with expert-led weekend coaching sessions covering every tested subject - from dental sciences and pharmacology to ethics, law, and clinical dentistry. Includes past paper analysis, study materials, and ongoing support through to exam day.",
    href: "/courses/adc-written-exam/adc-written-exam-coaching",
    image: "/images/courses/adc-written-exam-course.webp",
    category: "ADC Written Exam",
    duration: "6",
    durationLabel: "6 months",
    location: "Online",
    startTime: "Weekend sessions",
    fee: "$ 1,499 (AUD)",
    feeOriginal: "$ 1,899 (AUD)",
    availability: "Contact us for availability",
    features: ["6-month live coaching", "All written exam topics covered", "Past paper analysis", "Exam strategies by Dr. Samy", "Study materials included", "Ongoing support until exam day"],
    whoFor: ["ADC Written Exam candidates", "Overseas-trained dentists needing structured preparation"],
    whatYouLearn: ["Master all ADC written exam domains", "Exam technique and time management", "Past paper analysis skills"],
    modules: [],
    whatToBring: ["Notebook and study materials"],
    tasksLabel: "N/A",
    materialsIncluded: "Yes",
    demosIncluded: "N/A",
    accessDuration: "Until exam day",
    faq: [{ q: "How long is the coaching program?", a: "6 months of structured live coaching." }, { q: "Where are sessions held?", a: "Online via weekend sessions." }, { q: "What is covered?", a: "All ADC Written Exam topics plus past paper analysis." }, { q: "What is the fee?", a: "$1,499 (AUD)." }],
    stripeUrl: "",
  },
  {
    title: "Supervised Skilled OSCE Practice – Half Day",
    description: "Half-day supervised practice session with expert guidance. Perfect for refining your technique with real-time feedback.",
    longDescription: "Half-day supervised practice with expert guidance. Perfect for refining your technique with real-time feedback.",
    href: "/courses/others/supervised-skilled-osce-practice-half-day",
    image: "",
    category: "Others",
    duration: "Half",
    durationLabel: "Half day",
    location: "Lavanika Academy, Melbourne",
    startTime: "9:30 am to 12:30 pm",
    fee: "$ 650 (AUD)",
    availability: "Contact us for availability",
    features: ["Supervised practice", "Real-time feedback", "Expert guidance", "All skilled stations"],
    whoFor: ["ADC candidates wanting focused practice", "Dentists seeking expert guidance"],
    whatYouLearn: ["Refine technique with expert supervision", "Identify improvement areas"],
    modules: [],
    whatToBring: ["Eyewear", "Instruments (optional)"],
    tasksLabel: "All skilled tasks",
    materialsIncluded: "Provided",
    demosIncluded: "Not included",
    accessDuration: "N/A",
    faq: [{ q: "How long is the session?", a: "Half day." }, { q: "Where is it held?", a: "Lavanika Academy, Melbourne." }, { q: "What is the fee?", a: "$650 (AUD)." }],
    stripeUrl: "",
  },
  {
    title: "Unsupervised Skilled OSCE Practice – Half Day",
    description: "Half-day unsupervised practice session for independent skill refinement at your own pace.",
    longDescription: "Half-day unsupervised practice session for independent skill refinement at your own pace.",
    href: "/courses/others/unsupervised-skilled-osce-practice-half-day",
    image: "",
    category: "Others",
    duration: "Half",
    durationLabel: "Half day",
    location: "Lavanika Academy, Melbourne",
    startTime: "9:30 am to 12:30 pm",
    fee: "$ 450 (AUD)",
    availability: "Contact us for availability",
    features: ["Unsupervised practice", "Flexible scheduling", "All equipment provided", "Independent skill building"],
    whoFor: ["Candidates wanting independent practice", "Dentists who prefer self-directed study"],
    whatYouLearn: ["Practice at your own pace", "Build muscle memory and confidence"],
    modules: [],
    whatToBring: ["Eyewear", "Instruments (optional)"],
    tasksLabel: "All skilled tasks",
    materialsIncluded: "Provided",
    demosIncluded: "Not included",
    accessDuration: "N/A",
    faq: [{ q: "How long is the session?", a: "Half day." }, { q: "Where is it held?", a: "Lavanika Academy, Melbourne." }, { q: "What is the fee?", a: "$450 (AUD)." }],
    stripeUrl: "",
  },
  {
    title: "Supervised Chair Hire – 1 Day",
    description: "Full-day supervised chair hire with expert oversight for focused clinical practice.",
    longDescription: "Full-day supervised chair hire with expert oversight for focused clinical practice.",
    href: "/courses/others/supervised-chair-hire-1-day",
    image: "",
    category: "Others",
    duration: "1",
    durationLabel: "1 day",
    location: "Lavanika Academy, Melbourne",
    startTime: "9:30 am to 4:30 pm",
    fee: "$ 450 (AUD)",
    availability: "Contact us for availability",
    features: ["Full-day chair hire", "Supervised session", "All equipment included", "Expert oversight"],
    whoFor: ["Candidates needing dedicated practice time", "Dentists wanting expert supervision"],
    whatYouLearn: ["Focused practice with expert oversight", "Refine technique and workflow"],
    modules: [],
    whatToBring: ["Eyewear and loupes", "Instruments (optional)"],
    tasksLabel: "N/A",
    materialsIncluded: "Provided",
    demosIncluded: "Not included",
    accessDuration: "N/A",
    faq: [{ q: "How long is the session?", a: "Full day (9:30 am to 4:30 pm)." }, { q: "Where is it held?", a: "Lavanika Academy, Melbourne." }, { q: "What is the fee?", a: "$450 (AUD)." }],
    stripeUrl: "",
  },
  {
    title: "Unsupervised Chair Hire – 1 Day",
    description: "Full-day unsupervised chair hire for independent practice with full access to equipment and facilities.",
    longDescription: "Full-day unsupervised chair hire for independent practice with full access to equipment and facilities.",
    href: "/courses/others/unsupervised-chair-hire-1-day",
    image: "",
    category: "Others",
    duration: "1",
    durationLabel: "1 day",
    location: "Lavanika Academy, Melbourne",
    startTime: "9:30 am to 4:30 pm",
    fee: "$ 320 (AUD)",
    availability: "Contact us for availability",
    features: ["Full-day chair hire", "Unsupervised access", "All equipment included", "Flexible scheduling"],
    whoFor: ["Candidates wanting independent practice", "Dentists needing flexible scheduling"],
    whatYouLearn: ["Self-directed practice", "Build speed and confidence"],
    modules: [],
    whatToBring: ["Eyewear and loupes", "Instruments (optional)"],
    tasksLabel: "N/A",
    materialsIncluded: "Provided",
    demosIncluded: "Not included",
    accessDuration: "N/A",
    faq: [{ q: "How long is the session?", a: "Full day (9:30 am to 4:30 pm)." }, { q: "Where is it held?", a: "Lavanika Academy, Melbourne." }, { q: "What is the fee?", a: "$320 (AUD)." }],
    stripeUrl: "",
  },
  {
    title: "Technical Skills Online Assessment – 1 Month",
    description: "Upload your technical work for expert assessment over 1 month. Get detailed feedback on your technique and progress.",
    longDescription: "Upload your technical work for expert assessment over 1 month. Get detailed feedback on your technique and progress.",
    href: "/courses/others/technical-skills-online-assessment-1-month",
    image: "",
    category: "Others",
    duration: "1",
    durationLabel: "1 month",
    location: "Online",
    startTime: "Flexible",
    fee: "$ 499 (AUD)",
    availability: "Contact us for availability",
    features: ["Online assessment", "Expert feedback", "1-month access", "Progress tracking"],
    whoFor: ["Candidates unable to attend onsite", "Dentists wanting remote assessment"],
    whatYouLearn: ["Receive expert feedback on technique", "Track progress over time"],
    modules: [],
    whatToBring: ["Camera for photos/videos of work"],
    tasksLabel: "Upload your work",
    materialsIncluded: "N/A",
    demosIncluded: "Not included",
    accessDuration: "1 month",
    faq: [{ q: "How does it work?", a: "Upload your technical work for expert assessment." }, { q: "How long is access?", a: "1 month." }, { q: "What is the fee?", a: "$499 (AUD)." }],
    stripeUrl: "",
  },
  {
    title: "Technical Task Demo",
    description: "A ~2 hour demo session (1 hour demonstration + 1 hour practice) covering key technical tasks with expert guidance.",
    longDescription: "A ~2 hour demo session (1 hour demonstration + 1 hour practice) covering key technical tasks with expert guidance.",
    href: "/courses/others/technical-task-demo",
    image: "",
    category: "Others",
    duration: "~2",
    durationLabel: "~2 hours (demo + 1 hr practice)",
    location: "Lavanika Academy, Melbourne",
    startTime: "Flexible",
    fee: "$ 450 (AUD)",
    availability: "Contact us for availability",
    features: ["Expert demonstration", "Guided practice", "Technique breakdown", "Q&A session"],
    whoFor: ["Candidates wanting task-specific guidance", "Dentists needing technique refinement"],
    whatYouLearn: ["Learn proper technique from experts", "Practice under guidance"],
    modules: [],
    whatToBring: ["Eyewear and loupes", "Instruments (optional)"],
    tasksLabel: "1 task demo + practice",
    materialsIncluded: "Provided",
    demosIncluded: "Yes",
    accessDuration: "N/A",
    faq: [{ q: "How long is the session?", a: "Approximately 2 hours (1 hr demo + 1 hr practice)." }, { q: "Where is it held?", a: "Lavanika Academy, Melbourne." }, { q: "What is the fee?", a: "$450 (AUD)." }],
    stripeUrl: "",
  },
]

export const heroStats = [
  { value: "Highest OSCE Pass Rate", suffix: "" },
  { value: "750+", suffix: " Courses Conducted" },
  { value: "100+", suffix: " Five-Star Reviews" },
]

export const quickLinks = [
  { title: "Our Courses", href: "/courses", description: "Communication OSCE, Skilled OSCE, Technical Skills, Mock Exams, ADC Written Exam & more" },
  { title: "About Us", href: "/about", description: "Our story, mission, values and the team behind Lavanika Academy" },
  { title: "Reviews", href: "/review", description: "Hear from 1,200+ successful ADC candidates across 25 countries" },
  { title: "Articles", href: "/articles", description: "Guides, tips and insights for your ADC exam journey" },
]

export const courses: Course[] = [
  {
    title: "Communication OSCE",
    description: "Prepare for ADC OSCE communication stations through interactive training focused on patient-centred care, structured feedback, and real-exam strategies by Dr Lavanika.",
    href: "/courses/communication-osce",
    price: "From $1,599 AUD",
    image: "/images/courses/communication-osce-category.webp",
  },
  {
    title: "Skilled OSCE",
    description: "Build your clinical confidence and procedural clarity across all ADC Skilled OSCE stations through guided coaching and hands-on practice — including X-rays, scaling, local anesthesia, extractions, pit and fissure sealants, matrix band placement, rubber dam application, and emergency response (CPR, syncope).",
    href: "/courses/skilled-osce",
    price: "From $899 AUD",
    image: "/images/courses/skilled-osce-category.webp",
  },
  {
    title: "Technical Skills",
    description: "Hands-on training for ADC technical stations — composite, amalgam, provisional, crown cutting, caries, endo, and infection control. Build precision, speed, and efficiency under real exam conditions.",
    href: "/courses/technical-skills",
    price: "From $3,000 AUD",
    image: "/images/courses/technical-skills-category.webp",
  },
  {
    title: "Mock Exams",
    description: "Simulate full ADC Clinical and Technical day exams under timed conditions with detailed feedback to improve station strategy and time management.",
    href: "/courses/mock-exams",
    price: "From $550 AUD",
    image: "/images/courses/mock-exams-category.webp",
  },
  {
    title: "ADC Written Exam",
    description: "Structured 6-month live coaching for the ADC Written Exam, covering all essential topics, past paper analysis, and exam strategies with Dr. Samy.",
    href: "/courses/adc-written-exam",
    price: "From $1,499 AUD",
    image: "/images/courses/adc-written-exam-category.webp",
  },
  {
    title: "Others",
    description: "Flexible, à la carte options to complement your ADC preparation — including supervised and unsupervised practice sessions, chair hire, online task assessment, and task demos.",
    href: "/courses/others",
    price: "From $320 AUD",
    image: "/images/courses/technical-skills-category.webp",
  },
]

export const features = [
  { icon: "LiveIcon", title: "Live Expert Sessions", description: "Real-time insights & clarification" },
  { icon: "BookIcon", title: "Comprehensive Study Resources", description: "Up-to-date study resources that simplify complex ADC concepts" },
  { icon: "UsersIcon", title: "Interactive Learning", description: "Personalized learning for ADC exam success" },
  { icon: "HeartIcon", title: "Interactive Sessions with Personal Attention", description: "We keep batches small for better clarity, discussion, and growth." },
  { icon: "TrendingUpIcon", title: "Always Aligned with Current Exam Trends", description: "Always updated to match the latest ADC standards and modern dentistry." },
  { icon: "StarIcon", title: "One-on-One Guidance for Every Learner", description: "Personalised feedback and mentor support that accelerate your progress." },
]

export const stats = [
  { value: 99, suffix: "%", label: "Highest OSCE Pass Rate" },
  { value: 750, suffix: "+", label: "Onsite Course conducted" },
  { value: 4000, suffix: "+hrs", label: "Communication sessions" },
  { value: 100, suffix: "+", label: "5⭐ Reviews" },
]

export const milestones = [
  { year: 2019, title: "A spark of mentorship", description: "Dr Lavanika began by hosting weekly study circles for the ADC written exam to support first-generation learners who needed a trusted guide in their ADC journey." },
  { year: 2022, title: "Building the academy", description: "Those living-room sessions evolved into a full academy with face-to-face Communication OSCE roleplays, Skilled OSCE courses, and onsite mock exams." },
  { year: 2024, title: "Expanding the academy", description: "We welcomed our first cohort for the newly designed 2-week onsite Technical Skills course." },
  { year: null, title: "Learning without limits", description: "Over 1,200+ candidates trained from more than 25 countries — and growing every batch." },
]

export const values = [
  { title: "Empathy", description: "We know this journey is demanding — not just academically, but personally. Our team has walked the ADC path and we design every course with that lived experience in mind." },
  { title: "Clarity", description: "The ADC curriculum is complex. We break it down into structured, actionable frameworks so you always know exactly what to focus on and why." },
  { title: "Excellence", description: "We hold ourselves and our students to high standards — not to intimidate, but because we believe every candidate is capable of passing with distinction when guided well." },
  { title: "Community", description: "We succeed together. Our Facebook groups, batch WhatsApp chats, and peer networks mean you are never preparing alone — no matter where in the world you are." },
]

export const team: StaffMember[] = [
  {
    name: "Dr Lavanika",
    role: "Founder & Head Instructor",
    bio: "Cleared the ADC pathway with distinction. Known for her structured teaching style and warm, patient-focused coaching.",
  },
  {
    name: "Dr Mahmoud",
    role: "Technical Skills Coach",
    bio: "A restorative dentistry specialist who has cleared the ADC and leads our technical skills training with clarity and exam-focused insight.",
  },
  {
    name: "Alice",
    role: "Executive Assistant",
    bio: "A detail-focused professional overseeing IT, marketing, and accounts — ensuring everything works seamlessly behind the scenes.",
  },
]

export const reviews = [
  { name: "amish agarwal", date: "30 May 2026", text: "I would like to express my heartfelt gratitude to Dr. Lavanika and Dr. Mahmood for their outstanding support and guidance throughout my ADC journey...", url: "https://share.google/gft5Bt3aDrUtdvqZg" },
  { name: "Meena Rathi", date: "30 May 2026", text: "I enrolled in Dr Lavanika's communication osces course for ADC part 2 and it was an invaluable experience...", url: "https://share.google/7in1WGi49yH9KSs1E" },
  { name: "harsha vardan", date: "29 May 2026", text: "I attended the Communication OSCEs course by Dr. Lavanika, and it was a very nice experience overall...", url: "https://share.google/6j8ygSo69fak0Yflt" },
  { name: "Yashodha Mendis", date: "March 2026", text: "A tribute to a great mentor. My dearest Dr Lavanika, I was able to clear my ADC part 2 exam in my first attempt. Throughout the journey the biggest challenge I faced was the communication osce. Dr Lavanika's teaching and approach is excellent. I always had faith in her guidance and it paid off brilliantly. Highly recommended for anyone preparing for the ADC exams.", url: "" },
  { name: "Sania Augestine", date: "March 2026", text: "Dr Lavanika is the best mentor for ADC part 2. I did the communication course and work under supervision with Dr Lavanika before my exam. I am pretty sure that helped me to clear ADC part 2. Dr Lavanika's communication materials and explanations are unique — they help you stand different from the rest. Grateful for her support throughout this challenging journey.", url: "" },
  { name: "Priya Sharma", date: "February 2026", text: "I joined the Skilled OSCE course after struggling on my own for months. Dr Lavanika's structured approach and detailed feedback transformed my preparation. The mock exams were incredibly realistic and prepared me well for the actual assessment. Cleared on my first attempt!", url: "" },
]

export const announcements: Announcement[] = [
  {
    title: "June-2026 Communication OSCE batch bookings closed! Sep-2026 booking in progress!",
    date: "June 2026",
    description: "Our June Communication OSCE batch is now full. We are now accepting enrolments for the September 2026 batch. Secure your place early.",
    category: "Course Update",
  },
  {
    title: "Technical Skills 2-week intensive — enrol now to secure your place.",
    date: "June 2026",
    description: "Our 2-week onsite Technical Skills intensive course is now open for enrolment. Limited seats available for hands-on ADC technical training.",
    category: "Course Update",
  },
  {
    title: "ADC Part 2 Exam: The Complete Guide for Overseas Dentists (2026)",
    date: "May 2026",
    description: "Everything you need to know about the ADC Part 2 practical examination — what it is, how it works, what happens on exam day, and how to prepare.",
    category: "Guide",
  },
  {
    title: "Chunk and Check: How to Explain a Biopsy for a Tongue Ulcer",
    date: "March 2026",
    description: "Learn how to use the Chunk and Check method to guide patients through a biopsy conversation — shifting their focus from fear to clarity.",
    category: "Article",
  },
  {
    title: "A Journey of Resilience and Triumph",
    date: "March 2025",
    description: "A Journey of Resilience and Triumph: A Heartfelt Tribute to Success",
    category: "Story",
  },
]

export interface Article {
  title: string
  date: string
  description: string
  image: string
  tags: string[]
  href: string
}

export const articles: Article[] = [
  {
    title: "ADC Part 2 Exam: The Complete Guide for Overseas Dentists (2026)",
    date: "May 13, 2026",
    description: "Everything you need to know about the ADC Part 2 practical examination — what it is, how it works, what happens on exam day, and how to prepare. Your complete 2026 guide from Lavanika Academy.",
    image: "/images/articles/adc-part-2-guide.webp",
    tags: ["adc", "communication osce"],
    href: "/articles/adc-part-2-complete-guide-2026",
  },
  {
    title: "ADC Blueprint for Written Examination: The Complete Guide for Overseas-Trained Dentists (2026)",
    date: "April 10, 2026",
    description: "Everything you need to know about the ADC blueprint for the written examination. Understand domains, disciplines, clusters, question format, and how to use the blueprint to pass the ADC exam in 2026.",
    image: "/images/articles/adc-blueprint-image.webp",
    tags: ["written exam", "adc"],
    href: "/articles/adc-written-exam-blueprint-2026",
  },
  {
    title: "Chunk and Check: How to Explain a Biopsy for a Tongue Ulcer",
    date: "March 21, 2026",
    description: "Learn how to use the Chunk and Check method to guide patients through a biopsy conversation — shifting their focus from fear to clarity.",
    image: "/images/articles/article-9.webp",
    tags: ["communication osce"],
    href: "/articles/chunk-and-check-biopsy-tongue-ulcer",
  },
  {
    title: "ADC Written Exam 2026",
    date: "October 3, 2025",
    description: "Learn about ADC Written Exam 2026 — what to expect, key topics, and how to prepare effectively.",
    image: "/images/articles/article-1.webp",
    tags: ["written exam"],
    href: "/articles/adc-written-exam-2026",
  },
  {
    title: "ADC Technical Skills: Day 2 Setup Checklist",
    date: "April 5, 2025",
    description: "What to pack, prepare, and practice for your technical exam day — a comprehensive checklist for ADC Technical Skills Day 2.",
    image: "/images/articles/article-3.webp",
    tags: ["technical skills"],
    href: "/articles/adc-technical-skills",
  },
  {
    title: "A Journey of Resilience and Triumph",
    date: "March 16, 2025",
    description: "A Journey of Resilience and Triumph: A Heartfelt Tribute to Success",
    image: "/images/articles/article-2.webp",
    tags: ["skilled osce", "communication osce"],
    href: "/articles/a-journey-of-resilience-and-triumph",
  },
  {
    title: "ADC Written Exam Preparation Tips",
    date: "February 10, 2025",
    description: "Essential tips and strategies to help you prepare effectively for the ADC Written Examination.",
    image: "/images/articles/article-1.webp",
    tags: ["written exam"],
    href: "/articles/adc-written-exam-preparation-tips",
  },
  {
    title: "Understanding ADC OSCE Communication Stations",
    date: "January 15, 2025",
    description: "A comprehensive breakdown of the ADC OSCE communication stations and how to approach each type.",
    image: "/images/articles/article-9.webp",
    tags: ["communication osce"],
    href: "/articles/understanding-adc-osce-communication-stations",
  },
  {
    title: "Mastering ADC Skilled OSCE Procedures",
    date: "December 20, 2024",
    description: "Step-by-step guidance on mastering the key procedures tested in the ADC Skilled OSCE examination.",
    image: "/images/articles/article-2.webp",
    tags: ["skilled osce"],
    href: "/articles/mastering-adc-skilled-osce-procedures",
  },
  {
    title: "ADC Technical Skills: Common Mistakes to Avoid",
    date: "November 5, 2024",
    description: "Learn from common mistakes candidates make in the ADC Technical Skills exam and how to avoid them.",
    image: "/images/articles/article-3.webp",
    tags: ["technical skills"],
    href: "/articles/adc-technical-skills-common-mistakes",
  },
  {
    title: "Preparing for ADC Mock Exams: A Strategic Guide",
    date: "October 1, 2024",
    description: "A strategic guide to making the most of your ADC mock exams and using feedback to improve performance.",
    image: "/images/articles/adc-part-2-guide.webp",
    tags: ["mock exams"],
    href: "/articles/preparing-for-adc-mock-exams",
  },
]

export const services: Service[] = [
  {
    title: "Communication OSCE",
    description: "Interactive training focused on patient-centred care, structured feedback, and real-exam strategies by Dr Lavanika.",
    icon: "MessageSquare",
  },
  {
    title: "Skilled OSCE",
    description: "Guided coaching across all ADC Skilled OSCE stations including X-rays, scaling, local anesthesia, extractions, and emergency response.",
    icon: "Stethoscope",
  },
  {
    title: "Technical Skills",
    description: "Hands-on training for composite, amalgam, provisional, crown cutting, caries, endo, and infection control stations.",
    icon: "Wrench",
  },
  {
    title: "Mock Exams",
    description: "Full ADC Clinical and Technical day exams under timed conditions with detailed feedback.",
    icon: "ClipboardCheck",
  },
  {
    title: "ADC Written Exam Coaching",
    description: "Structured 6-month live coaching covering essential topics, past paper analysis, and exam strategies.",
    icon: "BookOpen",
  },
  {
    title: "Chair Hire & Practice",
    description: "Supervised and unsupervised practice sessions, chair hire, online task assessment, and task demos.",
    icon: "Calendar",
  },
]
